### PR TITLE
Added the atom editor

### PR DESCRIPTION
**Pull request by mr-cheffy**
Added the atom editor as it was ReactJs

### CODE REVIEW

**Comment by mauro-balades** [comment]
Need to change it to svg?

**Comment by mr-cheffy** [comment]
Preview:
atom

**Comment by jai-dewani** [comment]
I would have believed it is the original logo if I saw this anywhere randomly on the internet 🤣   
Nice one 💯

**Comment by mr-cheffy** [comment]
lmao

**Comment by MiranDaniel** [comment]
Awesome job!

**Comment by mr-cheffy** [comment]
@MiranDaniel  really?

**Comment by MiranDaniel** [comment]
> @MiranDaniel  really?

Yea it looks great!

**Comment by mr-cheffy** [comment]
Thanks!

**Comment by abhijit-hota** [comment]
It looks great but...the swap doesn't make much sense or is it just me? :sweat_smile:
We should do a Sublime Text <-> Atom.

**Comment by blryface** [comment]
oh

**Pull request closed without merging**
